alias o='open'
alias finder='open .'
alias flushdns='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'
alias showfiles='defaults write com.apple.finder AppleShowAllFiles -bool true; killall Finder'
alias hidefiles='defaults write com.apple.finder AppleShowAllFiles -bool false; killall Finder'
