#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET_ZSHRC="$HOME/.zshrc"
SOURCE_ZSHRC="$ROOT_DIR/.zshrc"
INSTALL_SCRIPT="$ROOT_DIR/scripts/install.sh"
MODULES_FILE="$HOME/.dotfiles.modules.sh"
MODULE_KEYS=(git go python node rust macos)
MODULE_LABELS=("Git" "Go" "Python" "Node.js" "Rust" "macOS")
MODULE_DEFAULTS=(1 1 1 1 1 1)
MODULE_VALUES=("${MODULE_DEFAULTS[@]}")

backup_existing_zshrc() {
  if [[ ! -e "$TARGET_ZSHRC" && ! -L "$TARGET_ZSHRC" ]]; then
    return
  fi

  if [[ -L "$TARGET_ZSHRC" ]] && [[ "$(readlink "$TARGET_ZSHRC")" == "$SOURCE_ZSHRC" ]]; then
    return
  fi

  local backup_path="$HOME/.zshrc.bak"
  if [[ -e "$backup_path" || -L "$backup_path" ]]; then
    backup_path="$HOME/.zshrc.bak.$(date +%Y%m%d%H%M%S)"
  fi

  mv "$TARGET_ZSHRC" "$backup_path"
  echo "Backed up existing .zshrc: $TARGET_ZSHRC -> $backup_path"

  if command -v diff >/dev/null 2>&1; then
    echo "Diff: $backup_path vs $SOURCE_ZSHRC"
    diff -u "$backup_path" "$SOURCE_ZSHRC" || true
  fi
}

load_module_values() {
  if [[ -f "$MODULES_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$MODULES_FILE"
  fi

  local i key var_name value
  for i in "${!MODULE_KEYS[@]}"; do
    key="${MODULE_KEYS[$i]}"
    var_name="DOTFILES_ENABLE_${key^^}"
    value="${!var_name:-${MODULE_DEFAULTS[$i]}}"
    if [[ "$value" == "1" ]]; then
      MODULE_VALUES[$i]=1
    else
      MODULE_VALUES[$i]=0
    fi
  done
}

print_module_menu() {
  local i marker
  echo "Select optional modules for the initial setup."
  echo "Enter numbers to toggle, then press Enter to continue."
  echo

  for i in "${!MODULE_KEYS[@]}"; do
    if [[ "${MODULE_VALUES[$i]}" == "1" ]]; then
      marker="[x]"
    else
      marker="[ ]"
    fi

    printf "%s %d. %s\n" "$marker" "$((i + 1))" "${MODULE_LABELS[$i]}"
  done

  echo
}

prompt_module_selection() {
  load_module_values

  if [[ ! -t 0 ]]; then
    echo "No interactive terminal detected. Using saved or default module selection."
    return
  fi

  local input token index
  while true; do
    print_module_menu
    read -r -p "Toggle numbers (example: 1 3), or press Enter to continue: " input
    [[ -z "$input" ]] && break

    for token in $input; do
      if [[ "$token" =~ ^[0-9]+$ ]]; then
        index=$((token - 1))
        if (( index >= 0 && index < ${#MODULE_KEYS[@]} )); then
          if [[ "${MODULE_VALUES[$index]}" == "1" ]]; then
            MODULE_VALUES[$index]=0
          else
            MODULE_VALUES[$index]=1
          fi
        fi
      fi
    done
  done
}

save_module_selection() {
  local i key upper

  {
    echo "# Generated by scripts/bootstrap.sh"
    for i in "${!MODULE_KEYS[@]}"; do
      key="${MODULE_KEYS[$i]}"
      upper="${key^^}"
      printf "DOTFILES_ENABLE_%s=%s\n" "$upper" "${MODULE_VALUES[$i]}"
    done
  } > "$MODULES_FILE"

  echo "Saved module selection: $MODULES_FILE"
}

mkdir -p "$HOME/.zsh/cache"
mkdir -p "$HOME/.config"

backup_existing_zshrc
prompt_module_selection
save_module_selection

ln -snf "$SOURCE_ZSHRC" "$TARGET_ZSHRC"
ln -snf "$ROOT_DIR/starship/starship.toml" "$HOME/.config/starship.toml"

"$INSTALL_SCRIPT"

echo "Bootstrapped dotfiles from: $ROOT_DIR"
echo "Linked: $TARGET_ZSHRC -> $SOURCE_ZSHRC"
echo "Linked: $HOME/.config/starship.toml -> $ROOT_DIR/starship/starship.toml"
echo "Configured modules: $MODULES_FILE"
echo "Executed: $INSTALL_SCRIPT"
