alias ls='ls -G'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -lah'
alias grep='grep --color=auto 2>/dev/null || grep'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias cls='clear'
alias reload='source ~/.zshrc'
alias mkdir='mkdir -p'
alias c='code .'

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias e='eza --icons=auto 2>/dev/null || eza'
alias ea='eza -a --icons=auto 2>/dev/null || eza -a'
alias el='eza -lah --git --icons=auto 2>/dev/null || eza -lah --git'
alias cat='bat --paging=never 2>/dev/null || command cat'

alias pn='pnpm'
alias px='pnpm exec'
alias nr='npm run'
alias nrd='npm run dev'
alias nrb='npm run build'
alias nrt='npm run test'
alias nx='npx'

alias uvx='uv run'
alias pt='pytest -q'

alias d='docker'
alias dc='docker compose'
alias dps='docker ps'
alias di='docker images'
alias dex='docker exec -it'
alias dl='lazydocker'

alias k='kubectl'
alias kgp='kubectl get pods'
alias kgs='kubectl get svc'
alias kgd='kubectl get deploy'
alias kctx='kubectx'
alias kns='kubens'
alias kl='kubectl logs'
alias ke='kubectl exec -it'
